#!/bin/bash
SCREENSHOT_DIR=~/Pictures/Screenshots
mkdir -p "$SCREENSHOT_DIR"
FILE="$SCREENSHOT_DIR/$(date +%Y%m%d-%H%M%S).png"

case "$1" in
    full)
        maim "$FILE"
        xclip -selection clipboard -t image/png < "$FILE"
        ;;
    area)
        maim -s "$FILE"
        xclip -selection clipboard -t image/png < "$FILE"
        ;;
esac

